version: "3.9"
services:
  wordpress:
    image: wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST:     ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER:     ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME:     ${WORDPRESS_DB_DATABASE}
    volumes:
     - wordpress:/var/www/html
     - ./intellitheme:/var/www/html/wp-content/themes/intellitheme

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_DATABASE}
      MYSQL_USER:     ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  wordpress:
